appId: com.dev.e2e

flows:
  - flows/expo-router-e2e.yaml

# Configuration for different test environments
ios:
  appId: com.dev.e2e
android:
  appId: com.dev.e2e

# Test settings
timeouts:
  default: 10000
  gesture: 5000
  animation: 2000

# Retry settings for flaky tests
retries: 2

# Screenshot settings for debugging
screenshots:
  onFailure: true
  directory: "screenshots"
